# Generated by Django 5.2.16 on 2026-07-14 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residents',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='resident_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='residents',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
