# Generated by Django 5.2.16 on 2026-07-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_residents_document_residents_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='residents',
            name='tracking_number',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
