# Generated by Django 5.2.16 on 2026-07-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_residents_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residents',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pre-approved', 'Pre-approved'), ('rejected', 'Rejected'), ('duplication', 'Duplication')], default='pending', max_length=20),
        ),
    ]
