# Generated by Django 5.2.16 on 2026-07-14 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_alter_residents_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='residents',
            name='thumb_mark',
            field=models.ImageField(blank=True, null=True, upload_to='thumb_marks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
