# Generated by Django 5.2.16 on 2026-07-14 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_residents_thumb_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='residents',
            name='biometric_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residents',
            name='document',
            field=models.FileField(default=14.069444444444445, upload_to='resident_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='residents',
            name='remarks',
            field=models.TextField(blank=True, default=14.069444444444445),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='residents',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pre-approved', 'Pre-approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('duplication', 'Duplication')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='residents',
            name='thumb_mark',
            field=models.ImageField(blank=True, null=True, upload_to='thumb_marks/'),
        ),
    ]
