# Generated by Django 5.2.16 on 2026-07-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0007_residents_biometric_date_alter_residents_document_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='residents',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'pre-approved', 'approved'])), fields=('full_name', 'document_type'), name='unique_active_resident_application'),
        ),
    ]
