# Generated by Django 5.2.16 on 2026-07-14 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0008_residents_unique_active_resident_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='residents',
            name='contact_number',
            field=models.CharField(default=14.069444444444445, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine mobile number (e.g. 09123456789 or +639123456789).', regex='^(09\\d{9}|\\+639\\d{9})$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residents',
            name='supporting_document',
            field=models.FileField(default=14.069444444444445, help_text='Upload a valid government-issued ID or other supporting document.', upload_to='resident_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
            preserve_default=False,
        ),
    ]
